version: '3.8'

services:
  backend:
    build:
      context: ./myheroes
      dockerfile: Dockerfile
    
    working_dir: /myheroes
    volumes:
      - ./myheroes:/myheroes
    
  frontend:
    build:
      context: ./angular-tour-of-heroes
      dockerfile: Dockerfile
    image: testfrontend:latest 
    working_dir: /angular-tour-of-heroes
    volumes:
      - ./angular-tour-of-heroes:/angular-tour-of-heroes

    entrypoint: ["ng", "build", "--watch=true", "--poll", "2000"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
    - ./angular-tour-of-heroes:/usr/share/nginx/html
    - ./nginx/conf.d:/etc/nginx/conf.d

