services:
  backend:
    build:
      context: ./myheroes
      dockerfile: Dockerfile
    
    working_dir: /myheroes
    volumes:
      - ./myheroes:/myheroes
    
  frontend:
    build:
      context: ./angular-tour-of-heroes
      dockerfile: Dockerfile
    
    volumes:
      - ./angular-tour-of-heroes:/angular-tour-of-heroes
    
    
    working_dir: /angular-tour-of-heroes
