# Generated by Django 4.2 on 2023-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='hero_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='hero_id',
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
